use crate::unit_conversion::UnitCategory;

#[derive(Debug, Clone, Copy)]
pub struct UnitDef {
    pub name: &'static str,
    pub aliases: &'static [&'static str],
    pub category: UnitCategory,
    pub scale: f64,
    pub offset: f64,
}

pub const UNITS: &[UnitDef] = &[
    // Length (base: meter)
    UnitDef {
        name: "mm",
        aliases: &[
            "mm",
            "millimeter",
            "millimetre",
            "millimeters",
            "millimetres",
        ],
        category: UnitCategory::Length,
        scale: 0.001,
        offset: 0.0,
    },
    UnitDef {
        name: "cm",
        aliases: &[
            "cm",
            "centimeter",
            "centimetre",
            "centimeters",
            "centimetres",
        ],
        category: UnitCategory::Length,
        scale: 0.01,
        offset: 0.0,
    },
    UnitDef {
        name: "m",
        aliases: &["m", "meter", "metre", "meters", "metres"],
        category: UnitCategory::Length,
        scale: 1.0,
        offset: 0.0,
    },
    UnitDef {
        name: "km",
        aliases: &["km", "kilometer", "kilometre", "kilometers", "kilometres"],
        category: UnitCategory::Length,
        scale: 1000.0,
        offset: 0.0,
    },
    UnitDef {
        name: "in",
        aliases: &["in", "inch", "inches"],
        category: UnitCategory::Length,
        scale: 0.0254,
        offset: 0.0,
    },
    UnitDef {
        name: "ft",
        aliases: &["ft", "foot", "feet"],
        category: UnitCategory::Length,
        scale: 0.3048,
        offset: 0.0,
    },
    UnitDef {
        name: "yd",
        aliases: &["yd", "yard", "yards"],
        category: UnitCategory::Length,
        scale: 0.9144,
        offset: 0.0,
    },
    UnitDef {
        name: "mi",
        aliases: &["mi", "mile", "miles"],
        category: UnitCategory::Length,
        scale: 1609.344,
        offset: 0.0,
    },
    // Mass (base: gram)
    UnitDef {
        name: "mg",
        aliases: &["mg", "milligram", "milligrams"],
        category: UnitCategory::Mass,
        scale: 0.001,
        offset: 0.0,
    },
    UnitDef {
        name: "g",
        aliases: &["g", "gram", "grams"],
        category: UnitCategory::Mass,
        scale: 1.0,
        offset: 0.0,
    },
    UnitDef {
        name: "kg",
        aliases: &["kg", "kilogram", "kilograms"],
        category: UnitCategory::Mass,
        scale: 1000.0,
        offset: 0.0,
    },
    UnitDef {
        name: "oz",
        aliases: &["oz", "ounce", "ounces"],
        category: UnitCategory::Mass,
        scale: 28.349_523_125,
        offset: 0.0,
    },
    UnitDef {
        name: "lb",
        aliases: &["lb", "lbs", "pound", "pounds"],
        category: UnitCategory::Mass,
        scale: 453.592_37,
        offset: 0.0,
    },
    // Volume (base: liter)
    UnitDef {
        name: "ml",
        aliases: &[
            "ml",
            "milliliter",
            "millilitre",
            "milliliters",
            "millilitres",
        ],
        category: UnitCategory::Volume,
        scale: 0.001,
        offset: 0.0,
    },
    UnitDef {
        name: "l",
        aliases: &["l", "liter", "litre", "liters", "litres"],
        category: UnitCategory::Volume,
        scale: 1.0,
        offset: 0.0,
    },
    UnitDef {
        name: "tsp",
        aliases: &["tsp", "teaspoon", "teaspoons"],
        category: UnitCategory::Volume,
        scale: 0.004_928_921_593_75,
        offset: 0.0,
    },
    UnitDef {
        name: "tbsp",
        aliases: &["tbsp", "tablespoon", "tablespoons"],
        category: UnitCategory::Volume,
        scale: 0.014_786_764_781_25,
        offset: 0.0,
    },
    UnitDef {
        name: "floz",
        aliases: &["floz", "fl-oz", "fl_oz", "fluidounce", "fluidounces"],
        category: UnitCategory::Volume,
        scale: 0.029_573_529_562_5,
        offset: 0.0,
    },
    UnitDef {
        name: "cup",
        aliases: &["cup", "cups"],
        category: UnitCategory::Volume,
        scale: 0.236_588_236_5,
        offset: 0.0,
    },
    UnitDef {
        name: "pt",
        aliases: &["pt", "pint", "pints"],
        category: UnitCategory::Volume,
        scale: 0.473_176_473,
        offset: 0.0,
    },
    UnitDef {
        name: "qt",
        aliases: &["qt", "quart", "quarts"],
        category: UnitCategory::Volume,
        scale: 0.946_352_946,
        offset: 0.0,
    },
    UnitDef {
        name: "gal",
        aliases: &["gal", "gallon", "gallons"],
        category: UnitCategory::Volume,
        scale: 3.785_411_784,
        offset: 0.0,
    },
    // Temperature (base: celsius)
    UnitDef {
        name: "c",
        aliases: &["c", "celsius", "centigrade"],
        category: UnitCategory::Temperature,
        scale: 1.0,
        offset: 0.0,
    },
    UnitDef {
        name: "f",
        aliases: &["f", "fahrenheit"],
        category: UnitCategory::Temperature,
        scale: 5.0 / 9.0,
        offset: -32.0,
    },
    UnitDef {
        name: "k",
        aliases: &["k", "kelvin", "kelvins"],
        category: UnitCategory::Temperature,
        scale: 1.0,
        offset: -273.15,
    },
];
